version: "3.8"
name: base

services:
    app:
        image: alemax-home-app
        build:
            target: dev
            dockerfile: Dockerfile
        volumes:
            - ./:/app
            - /app/node_modules
            - /app/.next
        ports:
            - "8383:3000"
